# Generated by Django 4.2.1 on 2023-05-20 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
